### ISSUE TITLE
Range of port number in broker configuration too short

### ISSUE THREAD

**Issue by jtornero** [nzfarmer1/telemetrylayer#4]
Port number in port configuration is just up to 9999. I've changed the plugin locally by just editing tl_brokerconfig.ui and later recompiling the ui, but don't know how to send a patch :(

Best regards

Jorge

**Comment by nzfarmer1** [comment]
Hi Jorge, thanks for pointing that out.  Will make a fix to the master soon.  Can I ask what you are using the tool for?

Andrew

**Comment by jtornero** [comment]
@nzfarmer1 Of course you can! 
Well,I was wondering if I could make a say-so runner tracking plugin for QGIS and I've recently discovered MQTT so first step was to see if the wheel was already invented. I found your plugin and it is not exactly what I want (as far as I have seen, need more experimenting) but is very inspiring (mostly the threading code) for what I want: a very simple plugin, just receiving coordinates from mobile devices via MQTT.

By the way I experienced some trouble while testing it (unicode issues) but I haven't been able to test it further.

Thanks for the plugin, all the best

Jorge

**Comment by nzfarmer1** [comment]
Yes, I had envisaged a tracker too. There is an example plugin that uses Telemetry Layer with a simple API.   Suggest you contact me directly.  andrew@agsense.co.nz.

**Comment by nzfarmer1** [comment]
Release made with ports up to 99999 supported in Git version.
